const eng = {
    'Nezavisimosti 11': 'Nezavisimosti 11',
    'Catalog' : 'Catalog',
    'Delivery' : 'Delivery',
    'Collections' : 'Collections',
    'Contacts' : 'Contacts',
    'Wine map' : 'Wine map',
    'Degustation' : 'Degustation',
    'The best taste is the taste of long-term wine': 'The best taste is the taste of long-term wine',
    'The ancient Greeks and Romans knew about the properties of aged wines. Some wines kept in sealed clay amphorae for many years. After the fall of the Roman Empire, there was practically no wine were kept. Most of the wines produced in Northern Europe were light-bodied, light in color and low in alcohol. Such wines could not be aged and aged over time. Wine producers did not consider it necessary bear the cost of aging the wine. By the 16th century, aged wines were being made only in the Mediterranean countries. AT In the 17th century, two events occurred that radically changed the wine industry in production of aged wines. The first was the use of corks and glass bottles, which made it possible to store wines in an almost hermetic environment; the second is the growing popularity of fortified wines such as port, Madeira and sherry. The addition of alcohol has been used as a preservative, allowing wines to age long sea voyages to England, America and the East Indies.': 'The ancient Greeks and Romans knew about the properties of aged wines. Some wines kept in sealed clay amphorae for many years. After the fall of the Roman Empire, there was practically no wine were kept. Most of the wines produced in Northern Europe were light-bodied, light in color and low in alcohol. Such wines could not be aged and aged over time. Wine producers did not consider it necessary bear the cost of aging the wine. By the 16th century, aged wines were being made only in the Mediterranean countries. AT In the 17th century, two events occurred that radically changed the wine industry in production of aged wines. The first was the use of corks and glass bottles, which made it possible to store wines in an almost hermetic environment; the second is the growing popularity of fortified wines such as port, Madeira and sherry. The addition of alcohol has been used as a preservative, allowing wines to age long sea voyages to England, America and the East Indies.',
    'New collections': 'New collections',
    'March 1980 Marseille Harvest': 'March 1980 Marseille Harvest',
    'The leading features of the Marseille black early grape variety are: deeply dissected, five-lobed, funnel-shaped, bare leaves with deep veins; brownish-wine-red unripened shoots; very early ripening, small black berries with a subtle nutmeg flavor.': 'The leading features of the Marseille black early grape variety are: deeply dissected, five-lobed, funnel-shaped, bare leaves with deep veins; brownish-wine-red unripened shoots; very early ripening, small black berries with a subtle nutmeg flavor.',
    'Colorful bottle of wine from Marseille': 'Colorful bottle of wine from Marseille',
    'Seedlings have a sprawling form of bushes. The tops of the shoots are bronze, shiny; leaves three-lobed, medium dissected. The central lobe of the leaf is less developed than the lateral ones. Autumn leaf color is wine red.': 'Seedlings have a sprawling form of bushes. The tops of the shoots are bronze, shiny; leaves three-lobed, medium dissected. The central lobe of the leaf is less developed than the lateral ones. Autumn leaf color is wine red.',
    'Learn more': 'Learn more',
    'Sign up for a tasting': 'Sign up for a tasting',
    'Sign up': 'Sign up',
    'Cooperation:': 'Cooperation:',
    'Corporate sales:': 'Corporate sales:',
    'Email:': 'Email:',
    'Request price:': 'Request price:',
    'Wine boutique Le Corte': 'Wine boutique Le Corte'
}