const rus = {
    'Nezavisimosti 11': 'Независимости 11',
    'Catalog': 'Каталог',
    'Delivery': 'Доставка',
    'Collections': 'Коллекции',
    'Contacts': 'Контакты',
    'Wine map': 'Винная карта',
    'Degustation': 'Дегустация',
    'The best taste is the taste of long-term wine': 'Лучший вкус, это вкус долголетнего вина',
    'The ancient Greeks and Romans knew about the properties of aged wines. Some wines kept in sealed clay amphorae for many years. After the fall of the Roman Empire, there was practically no wine were kept. Most of the wines produced in Northern Europe were light-bodied, light in color and low in alcohol. Such wines could not be aged and aged over time. Wine producers did not consider it necessary bear the cost of aging the wine. By the 16th century, aged wines were being made only in the Mediterranean countries. AT In the 17th century, two events occurred that radically changed the wine industry in production of aged wines. The first was the use of corks and glass bottles, which made it possible to store wines in an almost hermetic environment; the second is the growing popularity of fortified wines such as port, Madeira and sherry. The addition of alcohol has been used as a preservative, allowing wines to age long sea voyages to England, America and the East Indies.': 'Древние греки и римляне знали о свойствах выдержанных вин. Некоторые вина хранились в запечатанных глиняных амфорах много лет. После падения Римской империи вина практически не выдерживались. Большинство вин, производимых в Северной Европе были легкотекучими, светлого цвета и с низким уровнем алкоголя. Такие вина не могли выдерживаться и со временем зауксусивались. Производители вин не считали необходимым нести затраты на выдержку вина. К XVI веку выдержанные вина делались только в странах Средиземноморья. В XVII веке произошли два события, которые коренным образом изменили винодельческую промышленность в производстве выдержанных вин. Первое — использование пробки и стеклянных бутылок, что позволило хранить вина в практически герметичной среде; второе — рост популярности креплёных вин, таких как портвейн, мадера и херес. Добавление алкоголя использовалось в качестве консерванта, позволяя винам выдерживать длительные морские путешествия в Англию, Америку и Ост-Индию.',
    'New collections': 'Новинки коллекций',
    'March 1980 Marseille Harvest': 'Март 1980 Урожай Марселя',
    'The leading features of the Marseille black early grape variety are: deeply dissected, five-lobed, funnel-shaped, bare leaves with deep veins; brownish-wine-red unripened shoots; very early ripening, small black berries with a subtle nutmeg flavor.': 'Ведущие признаки сорта винограда Марсельский черный ранний: глубокорассеченные, пятилопастные, воронковидно изогнутые, голые, с углубленными жилками листья; коричневато-винно-красные невызревшие побеги; очень рано созревающие, небольшие черные ягоды с тонким мускатным привкусом.',
    'Colorful bottle of wine from Marseille': 'Красочная бутылка вина из Марселя',
    'Seedlings have a sprawling form of bushes. The tops of the shoots are bronze, shiny; leaves three-lobed, medium dissected. The central lobe of the leaf is less developed than the lateral ones. Autumn leaf color is wine red.': 'Саженцы имеют раскидистую форму кустов. Верхушки побегов бронзовые, блестящие; листья трехлопастные, среднерассеченные. Центральная лопасть листа менее развита, чем боковые. Осенняя окраска листьев винно-красная.',
    'Learn more': 'Узнать подробнее',
    'Sign up for a tasting': 'Запись на дегустацию',
    'Sign up': 'Записаться',
    'Cooperation:': 'Сотрудничество',
    'Corporate sales:': 'Корп.продажи',
    'Email:': 'Эл. почта',
    'Request price:': 'Запросить прайс',
    'Wine boutique Le Corte': 'Винный бутик Le Corte',
    'Catalog': 'Каталог',
    'Catalog': 'Каталог',
    'Catalog': 'Каталог',
    'Catalog': 'Каталог',
}